spring:
  application:
    admin: batch

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console


